CREATE TABLE [dbo].[users_202108120741] (
  [id] [int] NULL,
  [password] [nvarchar](100) NULL,
  [last_login] [datetime2] NULL,
  [is_superuser] [bit] NULL,
  [deleted] [nvarchar](255) NULL,
  [document_number] [nvarchar](50) NULL,
  [names] [nvarchar](50) NULL,
  [first_lastname] [nvarchar](50) NULL,
  [second_lastname] [nvarchar](50) NULL,
  [email] [nvarchar](100) NULL,
  [phone] [nvarchar](50) NULL,
  [civil_state] [nvarchar](50) NULL,
  [address_via] [nvarchar](50) NULL,
  [address_street] [nvarchar](100) NULL,
  [address_street_number] [nvarchar](50) NULL,
  [address_extra] [nvarchar](100) NULL,
  [address_urbanization] [nvarchar](100) NULL,
  [mobile_phone] [int] NULL,
  [gender] [nvarchar](50) NULL,
  [birth_date] [date] NULL,
  [accept_terms] [bit] NULL,
  [accept_data_usage] [bit] NULL,
  [accept_promotions] [bit] NULL,
  [is_staff] [bit] NULL,
  [is_active] [bit] NULL,
  [date_joined] [datetime2] NULL,
  [updated] [datetime2] NULL,
  [district_id] [int] NULL,
  [created] [datetime2] NULL,
  [validated_code_id] [int] NULL,
  [document_type] [nvarchar](50) NULL
)
ON [PRIMARY]
GO